### PR TITLE
fix: print span info with ctx  && add  CtxKVLog method

### PR DESCRIPTION
**Pull request by weedge**
`go get go.opentelemetry.io/otel@v1.11.1`

CHANGE:
1. add zap logger for zap fields, log kv pairs
```golang
func (l *Logger) CtxKVLog(ctx context.Context, level klog.Level, format string, kvs ...interface{})
```

2. fix: print span info with ctx

### CODE REVIEW

**Review by li-jin-gou — CHANGES_REQUESTED** [review]
need to sign cla

**Comment by weedge** [comment]
> need to sign cla
it's ok , signed the CLA

**Comment by CoderPoet** [comment]
Please fix the problem with code formatting

**Comment by weedge** [comment]
> Please fix the problem with code formatting

golangci-lint run --out-format=github-actions --path-prefix=./logging/zap -E gofumpt, it's ok

**Comment by rogerogers** [comment]
Seems not necessary to introduce logger, zap.Any is even slower than sugar.

**Comment by weedge** [comment]
> Seems not necessary to introduce logger, zap.Any is even slower than sugar.

I see https://github.com/uber-go/zap#performance  performance is good to me;
Please show some benchmark ?  i see zap.Any code  switch case ,  if defined type , no reflection,  like %v or %+v;

**Comment by weedge** [comment]
> > > Seems not necessary to introduce logger, zap.Any is even slower than sugar.
> > 
> > 
> > I see https://github.com/uber-go/zap#performance performance is good to me; Please show some benchmark ? i see zap.Any code switch case , if defined type , no reflection, like %v or %+v;
> 
> ```
> func BenchmarkZapAny(b *testing.B) {
> 	l, _ := zap.NewProduction()
> 	for i := 0; i < b.N; i++ {
> 		l.Info("bench", zap.String("key", "value"), zap.Any("key1", "value1"))
> 	}
> }
> 
> func BenchmarkZapSugar(b *testing.B) {
> 	l, _ := zap.NewProduction()
> 	s := l.Sugar()
> 	for i := 0; i < b.N; i++ {
> 		s.Infow("bench", "key", "value", zap.Any("key1", "value1"))
> 	}
> }
> ```
> 
> https://pkg.go.dev/go.uber.org/zap#hdr-Choosing_a_Logger
> 
> sugar has similar methods.

3q~

**Comment by ppzqh** [comment]
@CoderPoet Seems that all issues are fixed. Please help to take a look at this pr, thanks!

**Review by CoderPoet — APPROVED** [review]
/LGTM

**Pull request merged**
