### PR TITLE
chore: bump otel version

### PR DESCRIPTION
**Pull request by rogerogers**
chore: bump otel version

and other deps version

### CODE REVIEW

**Review by HeyJavaBean — APPROVED** [review]

**Review by GuangmingLuo — APPROVED** [review]

**Comment by wanghao0123** [comment]
@rogerogers hi, could you release a new version? thx

**Comment by wanghao0123** [comment]
@rogerogers hi, could you release a new version about this PR?

**Comment by rogerogers** [comment]
> @rogerogers hi, could you release a new version about this PR?

I don't have permission for this repository. You can update it with a hash first and then update it again after the release.

eg 

`github.com/kitex-contrib/obs-opentelemetry@c76e27f58391e7be84d8c71786151c72676aed8e`

**Comment by wanghao0123** [comment]
@rogerogers appreciate it. solved my problem. btw, how to generate this hash? I'm a rookie with golang.

**Comment by rogerogers** [comment]
> @rogerogers appreciate it. solved my problem. btw, how to generate this hash? I'm a rookie with golang.

The git commit hash.

**Pull request merged**
