### PR TITLE
Optimize Readme

### PR DESCRIPTION
**Pull request by CoderPoet**
- [x] add `Dependencies`
- [x] add `Configuration via environment variables`
- [x] remove unused link
- [x] correct the content: `baggage` -> `meta info`
- [x] optimize comment
- [x] optimize go mod

### CODE REVIEW

**Review by YangruiEmma — APPROVED** [review]

**Comment by Jeffwan** [comment]
@YangruiEmma @GuangmingLuo If you plan to use prow to merge the PR.  Following Github Approve won't work. The reason this PR has `approved` label is because the author is the owner. 
image


In order to merge the PR, you can add yourselves as reviewers and then leave `/lgtm`.

**Comment by Jeffwan** [comment]
I kind of forget that we configure organization member can all leave `lgtm` so I think we don't necessarily to configure `reviewers` in OWNER files.  One thing to notice is PR author can not self-lgtm his/her PR.

**Pull request merged**
